### ISSUE TITLE
inetc large file downloads

### ISSUE THREAD

**Issue by MaxHayman** [negrutiu/nsis#1]
Hello,

Great project by the way.

I would love to see support for large file downloads via inetc.

Is this something you may support?

**Comment by negrutiu** [comment]
Apart from the standard NSIS plugins, my builds include a few extra plugins
You may want to check out **`NSxfer`**...
It has extended support for file transfers, including large file (>4GB) operations
For a simple download, try: `NSxfer::Transfer /NOUNLOAD /URL "http://MyServer/MyFile" /LOCAL "$TEMP\MyFile" /END` in your script
There's a readme file in the Docs directory. It has a lot of info and usage examples
Enjoy!
